# name: Local CI-CD Pipeline

# on:
#   push:
#     branches: [ma]

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:

#       # 1. Checkout source code
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       - name: Check Workspace
#         run: |
#           Write-Host "Current directory:"
#           Get-Location
#           Write-Host "Files in current directory:"
#           Get-ChildItem
#           Write-Host "Searching for Dockerfile:"
#           Get-ChildItem -Path . -Filter Dockerfile -Recurse
#       - name: Check Docker Secrets
#         run: |
#           if ([string]::IsNullOrEmpty("${{ secrets.DOCKERHUB_USERNAME }}")) {
#             Write-Host "DOCKERHUB_USERNAME is EMPTY"
#           } else {
#             Write-Host "DOCKERHUB_USERNAME is available"
#           }
#           if ([string]::IsNullOrEmpty("${{ secrets.DOCKERHUB_TOKEN }}")) {
#             Write-Host "DOCKERHUB_TOKEN is EMPTY"
#           } else {
#             Write-Host "DOCKERHUB_TOKEN is available"
#           }
#       # 2. Login to Docker Hub
      
#       - name: Docker Login
#         run: |
#           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#       # 3. Build Docker image
#       - name: Build Docker Image
#         run: |
#           docker build -t praabhatkumar1991/devops-app:${{ github.run_number }} .
#       # 4. Push Docker image to Docker Hub
#       - name: Push Docker Image
#         run: |
#           docker push praabhatkumar1991/devops-app:${{ github.run_number }}
#       # 5. Update Kubernetes deployment with new image
#       - name: Deploy to Kubernetes
#         run: |
#           kubectl set image deployment/devops-app devops-app=praabhatkumar1991/devops-app:${{ github.run_number }}
#       # 6. Wait until rollout is completed
#       - name: Wait for Deployment
#         run: |
#           kubectl rollout status deployment/devops-app --timeout=120s
#       # 7. Verify deployment and pods
#       - name: Verify Kubernetes Deployment
#         run: |
#           echo "===== Deployment ====="
#           kubectl get deployment devops-app
#           echo "===== Pods ====="
#           kubectl get pods -o wide
#           echo "===== Services ====="
#           kubectl get svc
